# Generated by Django 5.1.2 on 2024-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire At')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
