# Generated by Django 5.1.2 on 2024-10-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Cancelled'), (2, 'Completed')], default=0, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['status', 'due_date'],
            },
        ),
    ]
